/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package covid.lab3;

import java.awt.*;

/**
 *
 * @author Usuario
 */
public class panel extends javax.swing.JFrame {
    Gestionador gest=new Gestionador();
    
    /**
     * Creates new form panel
     */
    public panel() {
        initComponents();
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/covid.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        fila = new javax.swing.JComboBox<>();
        columna = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        defrep1 = new javax.swing.JComboBox<>();
        nombre = new javax.swing.JTextField();
        fiebre = new javax.swing.JTextField();
        datos = new javax.swing.JButton();
        resul = new javax.swing.JLabel();
        background3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        generarlista = new javax.swing.JButton();
        change = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        lista = new javax.swing.JLabel();
        lista1 = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COVID 19");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(510, 320));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aislamiento COVID 19");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 170, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fila.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel2.add(fila, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 40, -1));

        columna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel2.add(columna, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 40, -1));

        jLabel2.setText("Columna");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, 20));

        jLabel3.setText("Fila");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 20, 20));

        jLabel4.setText("Fiebre");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 20));

        jLabel5.setText("Nombre");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel6.setText("Deficiencia Respiratoria");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 20));

        defrep1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "si", "no" }));
        defrep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defrep1ActionPerformed(evt);
            }
        });
        jPanel2.add(defrep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 60, -1));

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel2.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 60, -1));
        jPanel2.add(fiebre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 60, -1));

        datos.setText("Agregar datos");
        datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosActionPerformed(evt);
            }
        });
        jPanel2.add(datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        resul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(resul, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 210, 220));

        background3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/covidverde.png"))); // NOI18N
        jPanel2.add(background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 240));

        jTabbedPane1.addTab("Datos", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        generarlista.setText("Lista");
        generarlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarlistaActionPerformed(evt);
            }
        });
        jPanel3.add(generarlista, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        change.setText("Cambiar");
        change.setMaximumSize(new java.awt.Dimension(55, 23));
        change.setMinimumSize(new java.awt.Dimension(55, 23));
        change.setPreferredSize(new java.awt.Dimension(55, 23));
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });
        jPanel3.add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 90, -1));

        clear.setText("Limpiar");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel3.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));
        jPanel3.add(lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 190));
        jPanel3.add(lista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 210, 180));

        background2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/covidrojo.png"))); // NOI18N
        jPanel3.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 240));

        jTabbedPane1.addTab("Lista", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 490, 270));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/covid2.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosActionPerformed
        // TODO add your handling code here:
        int i,j;
        String n,d;
        double f;
        try{
            i=Integer.parseInt((String)fila.getSelectedItem())-1;
            j=Integer.parseInt((String)columna.getSelectedItem())-1;
            n=nombre.getText();
            d=(String)defrep1.getSelectedItem();
            f=Double.parseDouble(fiebre.getText());
            resul.setText(gest.Ingresardatos(i, j, n, d, f));
        }
        catch(Exception a){
            resul.setText("Faltan datos");
        }
    }//GEN-LAST:event_datosActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void generarlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarlistaActionPerformed
        // TODO add your handling code here:
        lista.setText(gest.mostrartabla());
    }//GEN-LAST:event_generarlistaActionPerformed

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        // TODO add your handling code here:
        lista1.setText(gest.compararmatriz());
    }//GEN-LAST:event_changeActionPerformed

    private void defrep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defrep1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_defrep1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        lista.setText("");
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JButton change;
    private javax.swing.JButton clear;
    private javax.swing.JComboBox<String> columna;
    private javax.swing.JButton datos;
    private javax.swing.JComboBox<String> defrep1;
    private javax.swing.JTextField fiebre;
    private javax.swing.JComboBox<String> fila;
    private javax.swing.JButton generarlista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lista;
    private javax.swing.JLabel lista1;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel resul;
    // End of variables declaration//GEN-END:variables
}
